### ISSUE TITLE
Elixir OOP

### ISSUE THREAD

**Issue by OvermindDL1** [mislavcimpersak/awesome-fun#13]
For the Elixir language there is the [`OOP`](https://github.com/wojtekmach/oop) library, entirely a recurring joke library in the Elixir language community.  The description from its repo:

> Are you tired of all of that modules, processes and functions nonsense? Do you want to just use classes, objects and methods? If so, use OOP [1] library in Elixir [2]!
> 
> [1] Actually, according to Alan Key, the inventor of OOP, "objects" is the lesser idea; the big idea is "messaging". In that sense, I can't agree more with Joe Armstrong's quote that Erlang is "possibly the only object-oriented language".
> 
> [2] Please don't. You've been warned.

**Comment by mislavcimpersak** [comment]
Very good lightning talk I must say! 😄 

https://www.youtube.com/watch?v=5EtV2JUU0Z4

Yeah, this is definitely going in 🤠
