### ISSUE TITLE
Submit to awesome upstream

### ISSUE THREAD

**Issue by nickserv** [mislavcimpersak/awesome-fun#15]
I meant to send them a pull request a while ago, but I had to wait until this project was old enough.

Anyway, I would do this myself, but I have a quick question. Should we categorize this under [Entertainment](https://github.com/sindresorhus/awesome#entertainment) or [Miscellaneous](https://github.com/sindresorhus/awesome#miscellaneous)?

**Comment by mislavcimpersak** [comment]
I've already submitted a pull request and filed it under *Miscellaneous*. 

You can see it [here](https://github.com/sindresorhus/awesome/pull/914). But no word from @sindresorhus regarding the pull request 😥

**Comment by mislavcimpersak** [comment]
💥  💥  💥 We've been merged! Hip hip hooray! 💥  💥  💥
