### ISSUE TITLE
Add /dev/null as a service

### ISSUE THREAD

**Issue by ChristianKreuzberger** [mislavcimpersak/awesome-fun#16]
See https://devnull-as-a-service.com

They provide /dev/null as a service :)

**Comment by mislavcimpersak** [comment]
That sounds utterly useless!

So it's a must for the list :) gonna add it

**Comment by mislavcimpersak** [comment]
added with https://github.com/mislavcimpersak/awesome-dev-fun/commit/b4f2cfba91e9641115f5634153c18a19b2e0743c

just referenced the wrong issue 🤕
