### ISSUE TITLE
E

### ISSUE THREAD

**Issue by Oxymoron290** [mislavcimpersak/awesome-fun#40]
https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by nickserv** [comment]
E

**Comment by mislavcimpersak** [comment]
wat.

**Comment by mislavcimpersak** [comment]
added in https://github.com/mislavcimpersak/awesome-dev-fun/commit/5a52048e8591464609d4ce72e4f5ad1c926bfd55 

i guess.

still... wat?

**Comment by Oxymoron290** [comment]
well... uhm... Did I just contribute to the death of my favorite repository?
https://linuxwit.ch/blog/2018/12/everything-that-lives-is-designed-to-end/
